services:
  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: carinsurance-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-carinsurance}
      POSTGRES_USER: ${POSTGRES_USER:-carins_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-carins_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - carinsurance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-carins_user} -d ${POSTGRES_DB:-carinsurance}"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
    driver: local

networks:
  carinsurance-network:
    driver: bridge
